### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by sabyasachi2505** [frifty-search/search-apps#1]
### Bug Descriptions

**All Use Cases - Bottom Section**
Cursor needs to change while hovering over the like/dislike button. Currently this seems misaligned.

**EMI Calculator**
1. Principal/Loan Amount gets animated into the text box if the text is empty - Stop this animation
2. Top 2 text boxes i.e. *Principal/Loan Amount* and *Annual Interest Rate (in %)* need to be aligned
3. Align the left border and right border of the *Calculate* button to the start/end of the text boxes
4. The result text i.e "Your EMI is ..." should be "XX payments needed, each worth YYY"
5. The result textbox should have the same dimensions as the Calculate button. Start where the Calculate button's left side starts and end with the button's right end. Wrap text post that. Keep the text center aligned instead of left aligned.
6. The Principal/Loan amount should have a comma format similar to currencies, we can do a comma after every 3 numerals
7. Similarly if the result showcases a higher amount, let's use the comma format similar to Point 6 above
8. Add "how to calculate emi", "how to calculate emis" to the search query -> app id mapping for this use case

**BMI Calculator** 

1. The toggle buttons on the right should be center aligned
2. lbs and ft should stay left aligned (as already is)
3. cm and kg should be right aligned
4. Change the top text to "Enter your weight in (kg/lb)" and "Enter your height in ..."
5. Instead of the text, show a bmi scale. Keep key markers at 18.5, 25, 30 etc and describe those sections as Underweight, Obese etc. Show the result as a divider line or an arrow pointing to where you are on the scale. Write text on top "You are here."

**Days from date**

1. Convert the result text from DD/MM/YYYY to DD-MMM-YYYY format

**Days between dates**

1. Add "days between date" to the search query -> app id mapping for this use case

**Age calculator**

1. Add "what is my age", "calculate age" to the search query -> app id mapping for this use case

**Comment by sabyasachi2505** [comment]
These bugs are based on the 1.0.4 version of the extension

**Comment by amlanpatnaikfrifty** [comment]
Good coverage of all bugs in the previous comment. 

Additional stuff:
1. For **Days between dates**

Looks like an error in Logic:

![Screenshot 2022-09-29 at 6 25 41 PM](https://user-images.githubusercontent.com/113872968/193037283-5b94c63d-cb50-46c2-a177-ceecb9e2c70e.png)

2. For **Days from date** and **Age calculator**

The result text should be Centre aligned? @sabyasachi2505 thoughts?

**Comment by StrangeNoob** [comment]
Bug Descriptions
All Use Cases - Bottom Section

- [x] Cursor needs to change while hovering over the like/dislike button. Currently this seems misaligned.


EMI Calculator

- [ ] Principal/Loan Amount gets animated into the text box if the text is empty - Stop this animation
- [x] Top 2 text boxes i.e. Principal/Loan Amount and Annual Interest Rate (in %) need to be aligned
- [x] Align the left border and right border of the Calculate button to the start/end of the text boxes
- [x] The result text i.e "Your EMI is ..." should be "XX payments needed, each worth YYY"
- [x] The result textbox should have the same dimensions as the Calculate button. Start where the Calculate button's left side starts and end with the button's right end. Wrap text post that. Keep the text center aligned instead of left aligned.
- [ ] The Principal/Loan amount should have a comma format similar to currencies, we can do a comma after every 3 numerals
- [x] Similarly if the result showcases a higher amount, let's use the comma format similar to Point 6 above
- [x] Add "how to calculate emi", "how to calculate emis" to the search query -> app id mapping for this use case

BMI Calculator

- [x] lbs and ft should stay left aligned (as already is)
- [x] The toggle buttons on the right should be center aligned
- [x] cm and kg should be right aligned
- [x] Change the top text to "Enter your weight in (kg/lb)" and "Enter your height in ..."
- [x] Instead of the text, show a bmi scale. Keep key markers at 18.5, 25, 30 etc and describe those sections as Underweight, Obese etc. Show the result as a divider line or an arrow pointing to where you are on the scale. Write text on top "You are here."

Days from date

- [x] Convert the result text from DD/MM/YYYY to DD-MMM-YYYY format


Days between dates

- [x] Add "days between date" to the search query -> app id mapping for this use case


Age calculator

- [x] Add "what is my age", "calculate age" to the search query -> app id mapping for this use case
